# Generated by Django 4.0.6 on 2022-11-17 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 17, 14, 24, 43, 854974, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='timestramp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 17, 14, 24, 54, 502016, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
